Controllers/FeatureVoteController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using App.Areas.Identity.Data;
using App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace App.Controllers
{
    public class FeatureVoteController : Controller
    {
        private readonly AppIdentityDbContext _context;

        public FeatureVoteController(AppIdentityDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var features = from f in _context.Feature select f;

            return View(await features
                .Include(m => m.Category)
                .OrderBy(m => m.VoteCount)
                .ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var feature = await _context.Feature
                .Include(m => m.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feature == null) return NotFound();

            return View(feature);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upvote(int? id)
        {
            if (id == null) return NotFound();

            var feature = await _context.Feature.FindAsync(id);
            if (feature == null) return NotFound();
// Check features -> users() exists

            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userVotes = from uv in _context.UserVote select uv;
            var exists = userVotes
                .Where(uv => uv.FeatureId == id)
                .Any(u => u.UserId == userId);

            if (!exists)
            {
                feature.VoteCount++;
                var userVote = new UserVote
                {
                    FeatureId = feature.Id,
                    UserId = userId,
                    CreatedAt = DateTime.Now
                };
                _context.Add(userVote);
                _context.Update(feature);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public Task<IActionResult> Downvote(int id)
        {
            throw new System.NotImplementedException();
        }
    }
}

Controllers/FeaturesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using App.Areas.Identity.Data;
using App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace App.Controllers
{
    [Authorize(Policy = "RequireAdmin")]
    public class FeaturesController : Controller
    {
        private readonly AppIdentityDbContext _context;

        public FeaturesController(AppIdentityDbContext context)
        {
            _context = context;
        }

        // GET: Features
        public async Task<IActionResult> Index(int categoryId)
        {
            ViewData["Categories"] = new SelectList(_context.Category, "Id", "Title");
            var features = from f in _context.Feature select f;

            if (categoryId != 0) features = features.Where(s => s.CategoryId == categoryId);

            return View(await features
                .Include(m => m.Category)
                .ToListAsync());
        }

        // GET: Features/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var feature = await _context.Feature
                .Include(m => m.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feature == null) return NotFound();

            return View(feature);
        }

        // GET: Features/Create
        public IActionResult Create()
        {
            ViewData["Categories"] = new SelectList(_context.Category, "Id", "Title");
            return View();
        }

        // POST: Features/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,DueDate,CategoryId")]
            Feature feature)
        {
            if (ModelState.IsValid)
            {
                feature.CreatedAt = DateTime.Now;
                feature.VoteCount = 0;
                _context.Add(feature);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return Create();
        }

        // GET: Features/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var feature = await _context.Feature.FindAsync(id);
            if (feature == null) return NotFound();

            ViewData["Categories"] = new SelectList(_context.Category, "Id", "Title");
            return View(feature);
        }

        // POST: Features/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,DueDate,CategoryId")]
            Feature feature)
        {
            if (id != feature.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(feature);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeatureExists(feature.Id))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return await Edit(id);
        }

        // GET: Features/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var feature = await _context.Feature
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feature == null) return NotFound();

            return View(feature);
        }

        // POST: Features/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var feature = await _context.Feature.FindAsync(id);
            _context.Feature.Remove(feature);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeatureExists(int id)
        {
            return _context.Feature.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Facade Features</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/datatables/datatables.min.css"/>
    <link rel="stylesheet" href="~/lib/fontawesome5/all.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>

                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="FeatureVote" asp-action="Index">Vote Now</a>
                    </li>
                    <li asp-authorize asp-policy="RequireAdmin" class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                    </li>
                    <li asp-authorize asp-policy="RequireAdmin" class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Features" asp-action="Index">Features</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Facade Features Vote
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/datatables/datatables.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>